## Maple Leaves Ltd. 
#### is a start-up company which makes herbs from different types of plants and its leaves. Currently the system they use to classify the trees which they import in a batch is quite manual. A labourer from his experience decides the leaf type and subtype of plant family. They have asked us to automate this process and remove any manual intervention from this process.Objective: To classify the plant leaves by various classifiers from different metrics of the leaves and to choose the best classifier for future reference.

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
plants = pd.read_csv('/Users/umangpandya/Desktop/Edureka Project/574_cert_proj_dataset_v3.0/train.csv')

In [4]:
plants.shape

(990, 194)

In [5]:
pd.set_option('display.max_columns', None)  
pd.set_option('display.expand_frame_repr', False)
pd.set_option('max_colwidth', -1)
    

In [6]:
plants

id                       species   margin1   margin2   margin3   margin4   margin5   margin6   margin7   margin8   margin9  margin10  margin11  margin12  margin13  margin14  margin15  margin16  margin17  margin18  margin19  margin20  margin21  margin22  margin23  margin24  margin25  margin26  margin27  margin28  margin29  margin30  margin31  margin32  margin33  margin34  margin35  margin36  margin37  margin38  margin39  margin40  margin41  margin42  margin43  margin44  margin45  margin46  margin47  margin48  margin49  margin50  margin51  margin52  margin53  margin54  margin55  margin56  margin57  margin58  margin59  margin60  margin61  margin62  margin63  margin64    shape1    shape2    shape3    shape4    shape5    shape6    shape7    shape8    shape9   shape10   shape11   shape12   shape13   shape14   shape15   shape16   shape17   shape18   shape19   shape20   shape21   shape22   shape23   shape24   shape25   shape26   shape27   shape28   shape29   shape30   shape31   shape32   shape33   shape34   shape35   shape36   shape37   shape38   shape39   shape40   shape41   shape42   shape43   shape44   shape45   shape46   shape47   shape48   shape49   shape50   shape51   shape52   shape53   shape54   shape55   shape56   shape57   shape58   shape59   shape60   shape61   shape62   shape63   shape64  texture1  texture2  texture3  texture4  texture5  texture6  texture7  texture8  texture9  texture10  texture11  texture12  texture13  texture14  texture15  texture16  texture17  texture18  texture19  texture20  texture21  texture22  texture23  texture24  texture25  texture26  texture27  texture28  texture29  texture30  texture31  texture32  texture33  texture34  texture35  texture36  texture37  texture38  texture39  texture40  texture41  texture42  texture43  texture44  texture45  texture46  texture47  texture48  texture49  texture50  texture51  texture52  texture53  texture54  texture55  texture56  texture57  texture58  texture59  texture60  texture61  texture62  texture63  texture64
0    1     Acer_Opalus                   0.007812  0.023438  0.023438  0.003906  0.011719  0.009766  0.027344  0.000000  0.001953  0.033203  0.013672  0.019531  0.066406  0.000000  0.029297  0.000000  0.031250  0.011719  0.000000  0.025391  0.023438  0.001953  0.000000  0.015625  0.000000  0.031250  0.000000  0.013672  0.029297  0.015625  0.011719  0.003906  0.025391  0.000000  0.001953  0.011719  0.009766  0.041016  0.037109  0.019531  0.000000  0.009766  0.021484  0.015625  0.007812  0.013672  0.027344  0.062500  0.000000  0.017578  0.031250  0.000000  0.044922  0.007812  0.025391  0.003906  0.013672  0.015625  0.013672  0.003906  0.005859  0.003906  0.019531  0.001953  0.000647  0.000609  0.000576  0.000553  0.000516  0.000496  0.000474  0.000453  0.000454  0.000429  0.000418  0.000410  0.000406  0.000398  0.000399  0.000389  0.000399  0.000416  0.000414  0.000430  0.000422  0.000437  0.000452  0.000467  0.000470  0.000484  0.000489  0.000490  0.000475  0.000486  0.000484  0.000500  0.000513  0.000511  0.000519  0.000513  0.000502  0.000498  0.000487  0.000471  0.000458  0.000440  0.000436  0.000427  0.000394  0.000385  0.000382  0.000370  0.000367  0.000373  0.000386  0.000389  0.000391  0.000414  0.000422  0.000434  0.000452  0.000471  0.000485  0.000512  0.000536  0.000553  0.000610  0.000661  0.049805  0.017578  0.003906  0.024414  0.001953  0.010742  0.035156  0.007812  0.039062  0.062500   0.000000   0.000000   0.007812   0.007812   0.000000   0.000000   0.047852   0.000000   0.054688   0.022461   0.000000   0.000977   0.018555   0.001953   0.008789   0.015625   0.044922   0.000000   0.037109   0.012695   0.028320   0.000000   0.019531   0.026367   0.005859   0.000000   0.004883   0.016602   0.034180   0.056641   0.006836   0.000977   0.022461   0.037109   0.004883   0.021484   0.035156   0.000977   0.004883   0.015625   0.000000   0.000000   0.006836   0.037109   0.007812   0.000000   0.002930   0.002930   0.035156   0.000000   0.000000   0.004883 

In [7]:
plantnames = plants.iloc[:,1]

In [8]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
plantnames = le.fit_transform(plantnames)

In [9]:
plantnames = pd.DataFrame(plantnames)

In [10]:
species = pd.DataFrame(plants.species)

In [11]:
ids = pd.DataFrame(plants.id)

In [12]:
plants

id                       species   margin1   margin2   margin3   margin4   margin5   margin6   margin7   margin8   margin9  margin10  margin11  margin12  margin13  margin14  margin15  margin16  margin17  margin18  margin19  margin20  margin21  margin22  margin23  margin24  margin25  margin26  margin27  margin28  margin29  margin30  margin31  margin32  margin33  margin34  margin35  margin36  margin37  margin38  margin39  margin40  margin41  margin42  margin43  margin44  margin45  margin46  margin47  margin48  margin49  margin50  margin51  margin52  margin53  margin54  margin55  margin56  margin57  margin58  margin59  margin60  margin61  margin62  margin63  margin64    shape1    shape2    shape3    shape4    shape5    shape6    shape7    shape8    shape9   shape10   shape11   shape12   shape13   shape14   shape15   shape16   shape17   shape18   shape19   shape20   shape21   shape22   shape23   shape24   shape25   shape26   shape27   shape28   shape29   shape30   shape31   shape32   shape33   shape34   shape35   shape36   shape37   shape38   shape39   shape40   shape41   shape42   shape43   shape44   shape45   shape46   shape47   shape48   shape49   shape50   shape51   shape52   shape53   shape54   shape55   shape56   shape57   shape58   shape59   shape60   shape61   shape62   shape63   shape64  texture1  texture2  texture3  texture4  texture5  texture6  texture7  texture8  texture9  texture10  texture11  texture12  texture13  texture14  texture15  texture16  texture17  texture18  texture19  texture20  texture21  texture22  texture23  texture24  texture25  texture26  texture27  texture28  texture29  texture30  texture31  texture32  texture33  texture34  texture35  texture36  texture37  texture38  texture39  texture40  texture41  texture42  texture43  texture44  texture45  texture46  texture47  texture48  texture49  texture50  texture51  texture52  texture53  texture54  texture55  texture56  texture57  texture58  texture59  texture60  texture61  texture62  texture63  texture64
0    1     Acer_Opalus                   0.007812  0.023438  0.023438  0.003906  0.011719  0.009766  0.027344  0.000000  0.001953  0.033203  0.013672  0.019531  0.066406  0.000000  0.029297  0.000000  0.031250  0.011719  0.000000  0.025391  0.023438  0.001953  0.000000  0.015625  0.000000  0.031250  0.000000  0.013672  0.029297  0.015625  0.011719  0.003906  0.025391  0.000000  0.001953  0.011719  0.009766  0.041016  0.037109  0.019531  0.000000  0.009766  0.021484  0.015625  0.007812  0.013672  0.027344  0.062500  0.000000  0.017578  0.031250  0.000000  0.044922  0.007812  0.025391  0.003906  0.013672  0.015625  0.013672  0.003906  0.005859  0.003906  0.019531  0.001953  0.000647  0.000609  0.000576  0.000553  0.000516  0.000496  0.000474  0.000453  0.000454  0.000429  0.000418  0.000410  0.000406  0.000398  0.000399  0.000389  0.000399  0.000416  0.000414  0.000430  0.000422  0.000437  0.000452  0.000467  0.000470  0.000484  0.000489  0.000490  0.000475  0.000486  0.000484  0.000500  0.000513  0.000511  0.000519  0.000513  0.000502  0.000498  0.000487  0.000471  0.000458  0.000440  0.000436  0.000427  0.000394  0.000385  0.000382  0.000370  0.000367  0.000373  0.000386  0.000389  0.000391  0.000414  0.000422  0.000434  0.000452  0.000471  0.000485  0.000512  0.000536  0.000553  0.000610  0.000661  0.049805  0.017578  0.003906  0.024414  0.001953  0.010742  0.035156  0.007812  0.039062  0.062500   0.000000   0.000000   0.007812   0.007812   0.000000   0.000000   0.047852   0.000000   0.054688   0.022461   0.000000   0.000977   0.018555   0.001953   0.008789   0.015625   0.044922   0.000000   0.037109   0.012695   0.028320   0.000000   0.019531   0.026367   0.005859   0.000000   0.004883   0.016602   0.034180   0.056641   0.006836   0.000977   0.022461   0.037109   0.004883   0.021484   0.035156   0.000977   0.004883   0.015625   0.000000   0.000000   0.006836   0.037109   0.007812   0.000000   0.002930   0.002930   0.035156   0.000000   0.000000   0.004883 

In [13]:
plants.drop(columns = ['id','species'],axis = 1,inplace = True)

In [14]:
plants = pd.concat([plants,plantnames],axis = 1)


In [15]:
plants.isna().sum()

margin1      0
margin2      0
margin3      0
margin4      0
margin5      0
margin6      0
margin7      0
margin8      0
margin9      0
margin10     0
margin11     0
margin12     0
margin13     0
margin14     0
margin15     0
margin16     0
margin17     0
margin18     0
margin19     0
margin20     0
margin21     0
margin22     0
margin23     0
margin24     0
margin25     0
margin26     0
margin27     0
margin28     0
margin29     0
margin30     0
            ..
texture36    0
texture37    0
texture38    0
texture39    0
texture40    0
texture41    0
texture42    0
texture43    0
texture44    0
texture45    0
texture46    0
texture47    0
texture48    0
texture49    0
texture50    0
texture51    0
texture52    0
texture53    0
texture54    0
texture55    0
texture56    0
texture57    0
texture58    0
texture59    0
texture60    0
texture61    0
texture62    0
texture63    0
texture64    0
0            0
Length: 193, dtype: int64

In [16]:
plants = pd.concat([plants, species],axis = 1)

In [17]:
plants.rename(columns ={0:'Label_Codes','species' : 'Species'}, inplace = True )

In [18]:
plants = pd.concat([plants,ids],axis = 1)

In [19]:
plants.head()

margin1   margin2   margin3   margin4   margin5   margin6   margin7  margin8   margin9  margin10  margin11  margin12  margin13  margin14  margin15  margin16  margin17  margin18  margin19  margin20  margin21  margin22  margin23  margin24  margin25  margin26  margin27  margin28  margin29  margin30  margin31  margin32  margin33  margin34  margin35  margin36  margin37  margin38  margin39  margin40  margin41  margin42  margin43  margin44  margin45  margin46  margin47  margin48  margin49  margin50  margin51  margin52  margin53  margin54  margin55  margin56  margin57  margin58  margin59  margin60  margin61  margin62  margin63  margin64    shape1    shape2    shape3    shape4    shape5    shape6    shape7    shape8    shape9   shape10   shape11   shape12   shape13   shape14   shape15   shape16   shape17   shape18   shape19   shape20   shape21   shape22   shape23   shape24   shape25   shape26   shape27   shape28   shape29   shape30   shape31   shape32   shape33   shape34   shape35   shape36   shape37   shape38   shape39   shape40   shape41   shape42   shape43   shape44   shape45   shape46   shape47   shape48   shape49   shape50   shape51   shape52   shape53   shape54   shape55   shape56   shape57   shape58   shape59   shape60   shape61   shape62   shape63   shape64  texture1  texture2  texture3  texture4  texture5  texture6  texture7  texture8  texture9  texture10  texture11  texture12  texture13  texture14  texture15  texture16  texture17  texture18  texture19  texture20  texture21  texture22  texture23  texture24  texture25  texture26  texture27  texture28  texture29  texture30  texture31  texture32  texture33  texture34  texture35  texture36  texture37  texture38  texture39  texture40  texture41  texture42  texture43  texture44  texture45  texture46  texture47  texture48  texture49  texture50  texture51  texture52  texture53  texture54  texture55  texture56  texture57  texture58  texture59  texture60  texture61  texture62  texture63  texture64  Label_Codes                Species  id
0  0.007812  0.023438  0.023438  0.003906  0.011719  0.009766  0.027344  0.0      0.001953  0.033203  0.013672  0.019531  0.066406  0.000000  0.029297  0.0       0.031250  0.011719  0.000000  0.025391  0.023438  0.001953  0.0       0.015625  0.000000  0.031250  0.000000  0.013672  0.029297  0.015625  0.011719  0.003906  0.025391  0.000000  0.001953  0.011719  0.009766  0.041016  0.037109  0.019531  0.000000  0.009766  0.021484  0.015625  0.007812  0.013672  0.027344  0.062500  0.000000  0.017578  0.031250  0.0       0.044922  0.007812  0.025391  0.003906  0.013672  0.015625  0.013672  0.003906  0.005859  0.003906  0.019531  0.001953  0.000647  0.000609  0.000576  0.000553  0.000516  0.000496  0.000474  0.000453  0.000454  0.000429  0.000418  0.000410  0.000406  0.000398  0.000399  0.000389  0.000399  0.000416  0.000414  0.000430  0.000422  0.000437  0.000452  0.000467  0.000470  0.000484  0.000489  0.000490  0.000475  0.000486  0.000484  0.000500  0.000513  0.000511  0.000519  0.000513  0.000502  0.000498  0.000487  0.000471  0.000458  0.000440  0.000436  0.000427  0.000394  0.000385  0.000382  0.000370  0.000367  0.000373  0.000386  0.000389  0.000391  0.000414  0.000422  0.000434  0.000452  0.000471  0.000485  0.000512  0.000536  0.000553  0.000610  0.000661  0.049805  0.017578  0.003906  0.024414  0.001953  0.010742  0.035156  0.007812  0.039062  0.062500   0.000000   0.000000   0.007812   0.007812   0.0        0.0        0.047852   0.0        0.054688   0.022461   0.0        0.000977   0.018555   0.001953   0.008789   0.015625   0.044922   0.000000   0.037109   0.012695   0.028320   0.000000   0.019531   0.026367   0.005859   0.0        0.004883   0.016602   0.034180   0.056641   0.006836   0.000977   0.022461   0.037109   0.004883   0.021484   0.035156   0.000977   0.004883   0.015625   0.000000   0.0        0.006836   0.037109   0.007812   0.000000   0.002930   0.002930   0.035156   0.0        0.0        0.004883   0.000000   0.025391   3          

In [20]:
y = plants.iloc[:,-3].values
x = plants.iloc[:,:192].values

In [21]:
from sklearn.preprocessing import StandardScaler
scx = StandardScaler()
x = scx.fit_transform(x)


In [22]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split (x,y, test_size=0.2)

I am not going to perform Logistic Regression since looking at the categories its vast and cannot be solved through Logistic regression

# KNearestNeighbors

In [23]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p=2)
knn.fit(x_train,y_train)
#Test Data
y_pred = knn.predict(x_test)
y_pred





array([98, 26, 41,  0, 65, 57, 11, 63, 25,  0, 72, 23, 54, 52, 31, 78,  5,
       61, 69, 89, 19, 29,  8, 65, 59, 68, 62, 84, 19, 61, 90,  0, 54, 82,
        1, 61, 71,  9, 47, 35, 88, 14, 84,  7, 68, 61, 80, 12, 63,  3, 71,
       56, 89,  0, 15, 66, 82, 82, 46,  4, 14, 27, 61, 93, 73, 18,  5, 75,
       32, 59, 39, 18, 72,  2, 97, 16, 81, 29, 76, 13, 52, 31, 88, 72, 44,
        3, 42, 84, 66, 28, 93, 49, 65, 35, 43, 20, 91, 22, 25, 94, 76, 76,
       19, 91, 18, 98,  3, 78, 39, 70,  4, 46, 68, 53, 43, 60, 20,  7, 68,
       85, 81, 36, 94, 45, 96, 49, 35, 54, 86, 75, 45,  3, 94, 15, 23, 66,
       19, 57, 97, 94, 76, 49, 10,  2, 45, 70, 18, 11, 88, 43, 10, 79,  1,
       34, 69, 50, 38, 43, 26, 89, 83,  7, 35, 70,  9, 32, 42, 39, 15, 92,
       56, 42, 12, 89, 70, 10, 39, 84, 49, 30, 41, 37, 44, 93, 53, 28, 24,
       17, 34, 41, 59, 33, 48, 21, 72, 64, 94, 51])

In [24]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score


In [25]:
accuracy_score(y_test, y_pred)

0.9696969696969697

# Decision Tree Classifier

In [26]:
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier(criterion = 'entropy')
dt.fit(x_train, y_train)
#Test Data
y_pred = dt.predict(x_test)
y_pred  


array([85, 26, 26,  0, 68, 57, 11, 59, 23,  0, 72, 25, 54, 52, 31, 78,  5,
       61,  3, 89, 19, 29,  8, 65, 80, 68, 62, 84, 19, 61, 61, 20, 54, 63,
        8, 61, 71,  9, 47, 35, 88, 93, 50,  7, 68, 61, 80, 12, 63, 79, 80,
       56, 89, 48, 15, 66, 82, 63, 46,  4, 14, 78, 22, 93, 18, 28, 72, 46,
       32, 59, 38, 18, 72, 94, 75, 16, 89, 29, 76, 48, 52, 75, 66, 72, 44,
       80, 84, 83, 66, 61, 93, 61, 65, 10, 43, 20, 91, 22, 25, 94, 76,  3,
       19, 91, 18, 18,  3, 78, 39,  5,  4, 46, 86, 53, 43, 68, 20, 49, 80,
       49, 81, 36, 95, 40, 96, 10, 35, 32, 30, 16, 45, 65, 76, 28, 23, 88,
       19, 57, 97, 94, 76, 14, 10, 69, 45, 70, 18, 11, 88, 96, 53, 79,  1,
       40,  3, 50, 36, 79, 78, 89, 83,  7, 35, 23,  9, 31, 27, 39, 28, 92,
       10, 42, 68, 89, 28, 10, 21, 84, 49, 30, 41, 37, 44, 32, 55, 15, 24,
       17, 36, 41, 95, 33,  0, 66,  5, 64, 94, 51])

In [27]:
accuracy_score(y_test, y_pred)

0.6060606060606061

# Random Forest

In [28]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(criterion = 'entropy')
rf.fit(x_train, y_train)
#Test Data
y_pred = rf.predict(x_test)
y_pred


/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


array([98,  1, 41,  0, 65, 57, 11, 59, 23,  0, 72, 23, 54, 52, 31, 78,  5,
       61, 69, 89, 19, 29,  8, 65, 71, 68, 62, 84, 19, 15, 61,  0, 54, 82,
        1, 61, 71,  9, 47, 35, 88,  1, 84,  7, 68, 61, 80, 12, 63,  3, 11,
       56, 89,  0, 15, 66, 82, 82, 46,  4, 14, 27, 55, 93, 73, 18,  5, 75,
       32, 59, 38, 18, 72,  2, 97, 16, 43, 29, 59, 13, 52, 27, 88, 72, 44,
       55, 42, 31, 66, 28, 93, 49, 65, 35, 43, 20, 86, 22, 25, 94, 76, 76,
       19, 91, 18, 98,  3,  9, 39, 10,  4, 46, 28, 53, 43, 60, 20, 49, 62,
       85, 60, 36, 94, 45, 96, 10, 35, 54, 86, 46, 45,  3, 94, 15, 23, 66,
       19, 57, 97, 94, 76,  1, 10,  2, 45, 70, 18, 11, 88, 43, 10, 79,  1,
       34, 69, 50, 38, 52, 26, 89, 83,  7, 35, 70,  9, 32, 42, 39, 15, 92,
       56, 42, 12, 89, 70, 10, 21, 84, 49, 30, 41, 34, 44, 35, 22, 28, 24,
       17, 34, 41, 59, 33, 48, 21, 72, 56, 45, 51])

In [29]:
accuracy_score(y_test, y_pred)

0.8484848484848485

# Naive Bayes

In [30]:
from sklearn.naive_bayes import GaussianNB
nb = GaussianNB()
nb.fit(x_train,y_train)
y_pred = nb.predict(x_test)
y_pred

array([98, 26, 26,  0, 78, 44, 11, 63, 25,  0, 87, 54, 54, 52, 31, 47,  5,
       96, 69, 17, 19, 29, 11, 20, 80, 50, 91, 69, 19, 85, 90, 48, 20, 82,
        1, 90, 80,  9, 47, 16, 88,  8, 84, 13, 69, 85, 80, 12, 63, 69, 71,
       56, 48, 87, 15, 66, 82, 59, 50,  1, 93, 27, 54, 93, 73, 18,  5, 75,
       32, 59, 69, 18, 72,  2, 97, 11, 81, 79, 76, 83, 69, 50, 36, 36, 77,
       85, 69, 84, 77, 28, 93, 69, 65,  1, 69, 20, 41, 22, 36, 94, 85, 85,
       19, 52, 18, 98, 50, 78, 40, 96, 11, 46, 46, 53, 47, 60, 20, 13, 69,
       85, 69, 36, 94, 45, 43, 69, 16, 54, 50, 75, 45, 85, 94, 67, 23, 73,
       19, 27, 77, 94, 85, 48, 10,  2, 45, 87, 18, 11, 88, 43, 10, 58, 11,
       34, 69, 50, 69, 43, 26, 91, 83,  7, 78, 70,  0, 32, 42, 84, 36, 92,
       85, 42, 12, 89, 78, 10, 39, 84, 49, 69, 41, 38, 77, 64, 85, 69, 43,
       50, 58, 41, 78, 33, 48, 73, 36, 51, 41, 51])

In [31]:
accuracy_score(y_test, y_pred)

0.5202020202020202

# Support Vector Machine

In [32]:
from sklearn.svm import SVC
sv = SVC (kernel = 'linear')
sv.fit(x_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='linear', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [33]:
y_pred = sv.predict(x_test)
y_pred

array([98, 26, 26,  0, 65, 57, 11, 63, 25,  0, 72, 23, 54, 52, 31, 78,  5,
       61, 69, 89, 19, 29,  8, 65, 71, 68, 62, 84, 19, 61, 90,  0, 54, 82,
        1, 61, 71,  9, 47, 35, 88, 14, 84,  7, 68, 61, 80, 12, 63,  3, 71,
       56, 89,  0, 15, 66, 82, 82, 46,  4, 14, 27, 61, 93, 73, 18,  5, 75,
       32, 59, 38, 18, 72,  2, 97, 16, 81, 29, 76, 13, 52, 68, 88, 72, 44,
       55, 42, 84, 66, 28, 93, 49, 65, 35, 43, 20, 91, 22, 25, 94, 76, 76,
       19, 91, 18, 98,  3, 78, 39, 70,  4, 46, 68, 53, 43, 60, 20,  7, 68,
       85, 81, 36, 94, 45, 96, 49, 35, 54, 86, 75, 45,  3, 94, 15, 23, 66,
       19, 57, 97, 94, 76, 49, 10,  2, 45, 70, 18, 11, 88, 43, 10, 79,  1,
       34, 69, 50, 38, 43, 26, 89, 83,  7, 35, 70,  9, 32, 42, 39, 15, 92,
       56, 42, 12, 89, 70, 10, 39, 84, 49, 30, 41, 37, 44, 64, 53, 28, 24,
       17, 34, 41, 59, 33, 48, 21, 72, 64, 94, 51])

In [34]:
accuracy_score(y_test, y_pred)

1.0

In [35]:
from sklearn.svm import SVC
sv = SVC (kernel = 'sigmoid')
sv.fit(x_train, y_train)


/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='sigmoid', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [36]:
y_pred = sv.predict(x_test)
y_pred


array([98, 26, 26,  0, 65, 57, 11, 63, 25,  0, 72, 23, 54, 52, 31, 74,  5,
       61, 69, 89, 19, 29,  8, 65, 71, 68, 62, 84, 47, 61, 90,  0, 54, 59,
        1, 61, 71,  9, 47, 35, 74, 14, 84,  7, 68, 61, 80, 12, 63,  3, 71,
       74, 89,  0, 15, 88, 59, 59, 74,  4, 14, 27, 61, 93, 73, 18,  5, 74,
       32, 59, 38, 18, 72,  2, 97, 16, 81, 29, 76, 13, 52, 31, 74, 72, 44,
       55, 42, 74, 88, 28, 93, 49, 65, 35, 43, 20, 91, 22, 25, 94, 76, 76,
       19, 91, 18, 98,  3, 74, 40, 70,  4, 74, 68, 53, 43, 60, 20,  7, 68,
       85, 81, 36, 94, 45, 96, 49, 35, 74, 86, 74, 45,  3, 94, 15, 23, 66,
       47, 57, 97, 94, 76, 49, 10,  2, 45, 70, 18, 11, 74, 43, 10, 79,  1,
       34, 69, 50, 38, 43, 26, 89, 83,  7, 35, 70,  9, 32, 42, 40, 15, 92,
       74, 42, 12, 89, 70, 10, 40, 84, 49, 30, 41, 37, 44, 93, 53, 28, 24,
       17, 34, 41, 59, 33, 48, 21, 72, 74, 94, 74])

In [37]:
accuracy_score(y_test, y_pred)

0.8636363636363636

In [38]:
from sklearn.svm import SVC
sv = SVC (kernel = 'rbf')
sv.fit(x_train, y_train)

/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [39]:
y_pred = sv.predict(x_test)
y_pred

array([98, 26, 26,  0, 65, 57, 11, 63, 25,  0, 72, 23, 54, 52, 31, 78,  5,
       61, 69, 89, 19, 29,  8, 65, 71, 68, 62, 84, 19, 61, 90,  0, 54, 82,
        1, 61, 71,  9, 47, 35, 88, 14, 84,  7, 68, 61, 80, 12, 63,  3, 71,
       56, 89,  0, 15, 66, 82, 82, 46,  4, 14, 27, 61, 93, 73, 18,  5, 75,
       32, 59, 38, 18, 72,  2, 97, 16, 81, 29, 76, 13, 52, 31, 88, 72, 44,
       69, 42, 84, 66, 28, 93, 49, 65, 35, 43, 20, 91, 22, 25, 94, 76, 76,
       19, 91, 18, 98,  3, 78, 39, 70,  4, 46, 68, 53, 43, 60, 20,  7, 68,
       85, 81, 36, 94, 45, 96, 49, 35, 54, 86, 75, 45,  3, 94, 15, 23, 66,
       19, 57, 97, 94, 76, 49, 10,  2, 45, 70, 18, 11, 88, 43, 10, 79,  1,
       34, 69, 50, 38, 43, 26, 89, 83,  7, 35, 70,  9, 32, 42, 40, 15, 92,
       56, 42, 12, 89, 70, 10, 39, 84, 49, 30, 41, 37, 44, 64, 53, 28, 24,
       17, 34, 41, 59, 33, 48, 21, 72, 64, 94, 51])

In [40]:
accuracy_score(y_test, y_pred)

0.9848484848484849

# We came with a conclusion that SVM Linear Kernal is the best fit model 

In [41]:
plants_test = pd.read_csv('/Users/umangpandya/Desktop/Edureka Project/574_cert_proj_dataset_v3.0/test.csv')

In [42]:
plants_test

id   margin1   margin2   margin3   margin4   margin5   margin6   margin7   margin8   margin9  margin10  margin11  margin12  margin13  margin14  margin15  margin16  margin17  margin18  margin19  margin20  margin21  margin22  margin23  margin24  margin25  margin26  margin27  margin28  margin29  margin30  margin31  margin32  margin33  margin34  margin35  margin36  margin37  margin38  margin39  margin40  margin41  margin42  margin43  margin44  margin45  margin46  margin47  margin48  margin49  margin50  margin51  margin52  margin53  margin54  margin55  margin56  margin57  margin58  margin59  margin60  margin61  margin62  margin63  margin64    shape1    shape2    shape3    shape4    shape5    shape6    shape7    shape8    shape9   shape10   shape11   shape12   shape13   shape14   shape15   shape16   shape17   shape18   shape19   shape20   shape21   shape22   shape23   shape24   shape25   shape26   shape27   shape28   shape29   shape30   shape31   shape32   shape33   shape34   shape35   shape36   shape37   shape38   shape39   shape40   shape41   shape42   shape43   shape44   shape45   shape46   shape47   shape48   shape49   shape50   shape51   shape52   shape53   shape54   shape55   shape56   shape57   shape58   shape59   shape60   shape61   shape62   shape63   shape64  texture1  texture2  texture3  texture4  texture5  texture6  texture7  texture8  texture9  texture10  texture11  texture12  texture13  texture14  texture15  texture16  texture17  texture18  texture19  texture20  texture21  texture22  texture23  texture24  texture25  texture26  texture27  texture28  texture29  texture30  texture31  texture32  texture33  texture34  texture35  texture36  texture37  texture38  texture39  texture40  texture41  texture42  texture43  texture44  texture45  texture46  texture47  texture48  texture49  texture50  texture51  texture52  texture53  texture54  texture55  texture56  texture57  texture58  texture59  texture60  texture61  texture62  texture63  texture64
0    4     0.019531  0.009766  0.078125  0.011719  0.003906  0.015625  0.005859  0.000000  0.005859  0.023438  0.005859  0.021484  0.076172  0.001953  0.035156  0.000000  0.001953  0.021484  0.001953  0.015625  0.009766  0.000000  0.000000  0.005859  0.007812  0.015625  0.000000  0.017578  0.029297  0.021484  0.001953  0.003906  0.025391  0.000000  0.013672  0.005859  0.042969  0.064453  0.031250  0.005859  0.003906  0.001953  0.021484  0.025391  0.005859  0.001953  0.023438  0.068359  0.000000  0.011719  0.031250  0.001953  0.011719  0.003906  0.007812  0.000000  0.009766  0.003906  0.054688  0.000000  0.000000  0.000000  0.052734  0.000000  0.000782  0.000828  0.000876  0.000927  0.000993  0.001060  0.001123  0.001205  0.001295  0.001393  0.001496  0.001601  0.001679  0.001590  0.001492  0.001398  0.001314  0.001238  0.001186  0.001125  0.001070  0.001005  0.000943  0.000886  0.000826  0.000783  0.000741  0.000702  0.000671  0.000668  0.000682  0.000705  0.000736  0.000763  0.000805  0.000861  0.000918  0.000979  0.001054  0.001132  0.001212  0.001279  0.001364  0.001420  0.001435  0.001436  0.001418  0.001359  0.001284  0.001206  0.001134  0.001055  0.001003  0.000941  0.000879  0.000819  0.000762  0.000717  0.000698  0.000688  0.000680  0.000695  0.000719  0.000737  0.112310  0.013672  0.011719  0.004883  0.010742  0.022461  0.055664  0.028320  0.040039  0.008789   0.006836   0.000000   0.008789   0.008789   0.000000   0.000000   0.017578   0.000977   0.025391   0.023438   0.000000   0.000977   0.023438   0.000000   0.004883   0.000000   0.013672   0.001953   0.045898   0.024414   0.045898   0.000000   0.000000   0.070312   0.011719   0.000000   0.000000   0.054688   0.024414   0.026367   0.000000   0.000977   0.010742   0.020508   0.013672   0.034180   0.025391   0.000000   0.014648   0.018555   0.000000   0.000000   0.000000   0.015625   0.006836   0.000000   0.015625   0.000977   0.015625   0.000000   0.000000   0.000000   0.003906   0.053711 
1    7     0.007812  0.005859  0.0644

In [43]:
x_test = plants_test.iloc[:,1:].values

In [44]:
x_test = scx.fit_transform(x_test)

# Support Vector Machine (Kernel Linear)

In [45]:
from sklearn.svm import SVC
sv = SVC (kernel = 'linear')
sv.fit(x_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='linear', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [46]:
y_pred = sv.predict(x_test)
y_pred

array([51, 50,  1, 19, 14,  3,  3, 28, 84,  8, 43, 74, 75, 10, 52, 46, 45,
       73, 13, 71, 61, 68, 57, 77,  1, 70, 28, 15, 35, 70, 53, 74, 47, 50,
        4, 36, 14, 55, 36, 93,  8, 32,  8,  9, 71, 70, 38, 23, 94, 18, 17,
        5, 55, 94, 14, 86, 62, 33, 51, 98, 88, 56, 21, 59, 65, 11, 48,  5,
       13,  4, 54, 57, 29,  7, 31, 98, 92, 84, 25, 10, 61, 43, 85, 24,  1,
        2, 23, 83, 40, 22, 48, 90, 25, 21, 37, 56, 41, 95,  7, 89, 98, 77,
        3, 12, 31, 84, 53, 96, 64, 72, 93, 93, 67, 30,  8, 88, 60, 87,  6,
       57, 34, 90, 60, 17, 75, 27, 51, 31, 39, 23, 24,  2, 41, 61, 24, 97,
       29, 28, 68, 81, 42, 51, 86, 62, 60, 52, 95, 64, 42, 96, 95, 20, 59,
       35, 86,  1, 26, 38, 43, 75, 20, 60, 46, 79, 22, 79, 69, 87, 65, 97,
       75, 21, 29, 21, 11, 10, 58, 94, 27, 22, 15, 45, 89, 54, 43,  5, 23,
       94, 40, 49, 89, 72, 36, 11, 81, 95, 18, 91, 29, 64, 80,  6, 78, 45,
       28,  9, 78, 90, 44, 89, 92, 13,  2, 59,  0, 96, 70, 32, 29, 78, 91,
       55, 44, 38,  5, 60

In [48]:
plants_test = pd.concat([pd.DataFrame(y_pred),plants_test], axis = 1)

In [50]:
plants_test.rename(columns = {0 : 'Prediction'}, inplace = True)

In [52]:
plants_test # for checking the prediction codes which is that plant we can check on train data set

Prediction    id   margin1   margin2   margin3   margin4   margin5   margin6   margin7   margin8   margin9  margin10  margin11  margin12  margin13  margin14  margin15  margin16  margin17  margin18  margin19  margin20  margin21  margin22  margin23  margin24  margin25  margin26  margin27  margin28  margin29  margin30  margin31  margin32  margin33  margin34  margin35  margin36  margin37  margin38  margin39  margin40  margin41  margin42  margin43  margin44  margin45  margin46  margin47  margin48  margin49  margin50  margin51  margin52  margin53  margin54  margin55  margin56  margin57  margin58  margin59  margin60  margin61  margin62  margin63  margin64    shape1    shape2    shape3    shape4    shape5    shape6    shape7    shape8    shape9   shape10   shape11   shape12   shape13   shape14   shape15   shape16   shape17   shape18   shape19   shape20   shape21   shape22   shape23   shape24   shape25   shape26   shape27   shape28   shape29   shape30   shape31   shape32   shape33   shape34   shape35   shape36   shape37   shape38   shape39   shape40   shape41   shape42   shape43   shape44   shape45   shape46   shape47   shape48   shape49   shape50   shape51   shape52   shape53   shape54   shape55   shape56   shape57   shape58   shape59   shape60   shape61   shape62   shape63   shape64  texture1  texture2  texture3  texture4  texture5  texture6  texture7  texture8  texture9  texture10  texture11  texture12  texture13  texture14  texture15  texture16  texture17  texture18  texture19  texture20  texture21  texture22  texture23  texture24  texture25  texture26  texture27  texture28  texture29  texture30  texture31  texture32  texture33  texture34  texture35  texture36  texture37  texture38  texture39  texture40  texture41  texture42  texture43  texture44  texture45  texture46  texture47  texture48  texture49  texture50  texture51  texture52  texture53  texture54  texture55  texture56  texture57  texture58  texture59  texture60  texture61  texture62  texture63  texture64
0    51          4     0.019531  0.009766  0.078125  0.011719  0.003906  0.015625  0.005859  0.000000  0.005859  0.023438  0.005859  0.021484  0.076172  0.001953  0.035156  0.000000  0.001953  0.021484  0.001953  0.015625  0.009766  0.000000  0.000000  0.005859  0.007812  0.015625  0.000000  0.017578  0.029297  0.021484  0.001953  0.003906  0.025391  0.000000  0.013672  0.005859  0.042969  0.064453  0.031250  0.005859  0.003906  0.001953  0.021484  0.025391  0.005859  0.001953  0.023438  0.068359  0.000000  0.011719  0.031250  0.001953  0.011719  0.003906  0.007812  0.000000  0.009766  0.003906  0.054688  0.000000  0.000000  0.000000  0.052734  0.000000  0.000782  0.000828  0.000876  0.000927  0.000993  0.001060  0.001123  0.001205  0.001295  0.001393  0.001496  0.001601  0.001679  0.001590  0.001492  0.001398  0.001314  0.001238  0.001186  0.001125  0.001070  0.001005  0.000943  0.000886  0.000826  0.000783  0.000741  0.000702  0.000671  0.000668  0.000682  0.000705  0.000736  0.000763  0.000805  0.000861  0.000918  0.000979  0.001054  0.001132  0.001212  0.001279  0.001364  0.001420  0.001435  0.001436  0.001418  0.001359  0.001284  0.001206  0.001134  0.001055  0.001003  0.000941  0.000879  0.000819  0.000762  0.000717  0.000698  0.000688  0.000680  0.000695  0.000719  0.000737  0.112310  0.013672  0.011719  0.004883  0.010742  0.022461  0.055664  0.028320  0.040039  0.008789   0.006836   0.000000   0.008789   0.008789   0.000000   0.000000   0.017578   0.000977   0.025391   0.023438   0.000000   0.000977   0.023438   0.000000   0.004883   0.000000   0.013672   0.001953   0.045898   0.024414   0.045898   0.000000   0.000000   0.070312   0.011719   0.000000   0.000000   0.054688   0.024414   0.026367   0.000000   0.000977   0.010742   0.020508   0.013672   0.034180   0.025391   0.000000   0.014648   0.018555   0.000000   0.000000   0.000000   0.015625   0.006836   0.000000   0.015625   0.000977   0.015625   0.000000   0.000000   0.000000   0.003906   0.053711 
1    50    